Repository madlabsinc/mevn-cli, pull requests merged in 2019-02, with the labels that each got.

#68 Refactor code
  package-lock.json
Labels: assigned

#75 warn user if git is not installed
  lib/deploy/git_repo.js
Labels: bug

#83 Update all instances of mevn within the list of commands #79
  lib/commands/initlib.js
Labels: docs

#88 Fix new project not created if a non-empty folder with the same name as boilerplate repo exists.
  lib/commands/init.js
Labels: bug
